In [7]:
! pip install numpy

In [8]:
import numpy as np


In [9]:
a = np.array([1,2,3,4,5,6,7,8])

In [10]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
type(a)

numpy.ndarray

In [5]:
import numpy as np


In [6]:
a = np.array([1,2,3,4,5,6,7,8])

In [9]:
a + 10



array([11, 12, 13, 14, 15, 16, 17, 18])

In [19]:
b = np.array([1,2,3,4,5,6,7,8])

In [20]:
b * a


array([ 1,  4,  9, 16, 25, 36, 49, 64])

In [23]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
c = np.array([[1,2,3],[1,2,3,],[1,2,3]])
c

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [33]:
d = np.arange(100).reshape(10,10)

In [35]:
d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [43]:
a = np.arange(5)
b = np.arange(5).reshape(5,-2)
b

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [40]:
a*b

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12],
       [ 0,  4,  8, 12, 16]])

In [3]:
import numpy as np



In [ ]:
np.array.